# Generated by Django 4.0.5 on 2022-07-05 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('course_old_fee', models.IntegerField(default=0)),
                ('course_fee', models.IntegerField(default=0)),
                ('course_photo', models.ImageField(default='corusPhoto\\image-not-found.jpg', upload_to='corusPhoto')),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_first', models.CharField(max_length=255)),
                ('heading_firs_description', models.TextField()),
                ('heading_second', models.CharField(max_length=255)),
                ('heading_second_description', models.TextField()),
                ('list_first', models.CharField(max_length=255)),
                ('list_first_description', models.TextField()),
                ('list_second', models.CharField(max_length=255)),
                ('list_second_description', models.TextField()),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeApp.course')),
            ],
            options={
                'db_table': 'Course Details',
            },
        ),
    ]
